# Site
name: "Ravi Kumar Pillai"
title: "Ravi Kumar Pillai"
description: "Author, Coach, Mentor and Consultant"
meta_description: "Author, Coach, Mentor and Consultant"
logo: ''
favicon: ''
paginate: 4
baseurl: ''
email: 'ravikumarpillai9@gmail.com'
# google_analytics: 'UA-46278016-1'
disqus: ''
sharethis: ''

# Authors
authors:
  Ravi:
    name: Ravi Kumar Pillai
    display_name: Ravi
    gravatar: 19014d4504a4a1ae409da01f7b6b4238
    email: ravikumarpillai9@gmail.com
    description: "Ravi Kumar Pillai is an author, Coach and Consultant based in Trivandrum and can be contacted at ravikumarpillai9@gmail.com"
# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge